services:
  db:
    image: docker.io/library/postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    networks:
      - postgres_network
  
networks:
  postgres_network:
    driver: bridge