name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black bandit pytest 
        pip install -r requirements.txt -r requirements-migrations.txt
    - name: Lint with Black
      run: black --check app tests
    - name: Run Security Scan with Bandit
      run: bandit -r app
    - name: Run Tests
      run: pytest tests